version = 0.1
[default.deploy.parameters]
stack_name = "sam-apps2"
resolve_s3 = true
s3_prefix = "sam-apps2"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
image_repositories = []
