AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Lambda functions to process SQS messages and handle S3 file uploads for PDF conversion to Base64.

Resources:
  # Define IAM Role for the Lambda functions
  LambdaFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "lambda-sqs-role-${AWS::StackName}"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Path: '/'
      Policies:
        - PolicyName: LambdaExecutionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              # Logging permissions
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: 'arn:aws:logs:*:*:*'

              # Permissions to interact with SQS
              - Effect: Allow
                Action:
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                Resource: 'arn:aws:sqs:us-east-1:928084763632:Redox-Webhook'

              # Permissions to read and write to S3
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource: 
                  - 'arn:aws:s3:::redox-base64/*'  # Destination bucket for base64
                  - 'arn:aws:s3:::redox-pdf/*'  # Source bucket for PDFs
                  - 'arn:aws:s3:::redox-s3/*'  # Added permission for redox-s3 bucket

              # Permissions to read from SSM (if applicable)
              - Effect: Allow
                Action:
                  - ssm:GetParameter
                Resource: 'arn:aws:ssm:us-east-1:*:parameter/*'

              # Permissions to read secrets from Secrets Manager (if applicable)
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: '*'

  # Commenting out S3 bucket-related resources for now

  # S3SourceBucket:
  #   Type: AWS::S3::Bucket
  #   DeletionPolicy: Retain  # Prevents deletion of the existing bucket
  #   Properties:
  #     BucketName: redox-pdf  # The bucket already exists

  # S3DestBucket:
  #   Type: AWS::S3::Bucket
  #   DeletionPolicy: Retain  # Prevents deletion of the existing bucket
  #   Properties:
  #     BucketName: redox-base64  # The bucket already exists

  # PDF to Base64 Lambda Function
  PdfToBase64Lambda:
    Type: AWS::Serverless::Function
    Properties: 
      CodeUri: ./dist
      Handler: src/pdf-to-base64-lambda.handler
      Runtime: nodejs18.x
      MemorySize: 512
      Timeout: 30
      Role: !GetAtt LambdaFunctionRole.Arn
      Environment:
        Variables:
          S3_SOURCE_BUCKET: "redox-s3"  # Commenting out the ref to the S3 bucket resource
          S3_DEST_BUCKET: "redox-base64"  # Commenting out the ref to the S3 bucket resource

  # Commenting out the S3 trigger permission
  # PdfToBase64LambdaBucketPermission:
  #   Type: AWS::Lambda::Permission
  #   Properties:
  #     Action: lambda:InvokeFunction
  #     FunctionName: !GetAtt PdfToBase64Lambda.Arn
  #     Principal: s3.amazonaws.com
  #     SourceArn: !GetAtt S3SourceBucket.Arn

  # Commenting out S3 event notification
  # S3BucketNotification:
  #   Type: AWS::S3::Bucket
  #   Properties:
  #     BucketName: !Ref S3SourceBucket
  #     NotificationConfiguration:
  #       LambdaConfigurations:
  #         - Event: s3:ObjectCreated:*
  #           Function: !GetAtt PdfToBase64Lambda.Arn

  # SQS Processing Lambda Function
  SqsProcessingLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./dist
      Handler: src/lambda.handler 
      Runtime: nodejs18.x
      MemorySize: 512
      Timeout: 30
      Role: !GetAtt LambdaFunctionRole.Arn
      Environment:
        Variables:
          SQS_QUEUE_URL: https://sqs.us-east-1.amazonaws.com/928084763632/Redox-Webhook
          S3_BUCKET_NAME: redox-s3
          FORM_POST_API_URL: https://webhook.site/2cd22442-bf89-4ca4-9e6b-f043b958b1be
          REDOX_KID: "gyNPIdN8e3hIIrwXHR77ZL7w2yKxyTH-eoDCJx1d5UA"
          REDOX_CLIENT_ID: "fb02b75b-edf3-42cf-9569-5e6cccffb42a"
          REDOX_PRIVATE_KEY: |
            -----BEGIN PRIVATE KEY-----
            MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQC3aemYSYxHfADG
            eK+hZU9yxdxDatEAMnHUnumlqDWVK/edSS5NwRaZWj+eCUWiSvvRrqQDMHMNS9Ys
            wW2kUW0797HZWfVU7crkjteFuVctS59U8dNDTyaNGzG0yAS2pMfFqjIDFlKvy5cB
            aCO8WEJT8PwTTTp2ofqWz7g140CsY9zDbIsNXs1VIjfNV6EZNuOuuvLTpbc0lIa9
            wFDbtI3BksKsZYIv7iR+Csk/ligvBbrg5uuAoeq2Fm6rPaCs7MHrZmQ9QS2z2dVP
            6dVBjQVsEtjmtMslS0QkAzYGImIPJ9MHZL6eX6UR7WNOBxRLZLid9JD9Fghcurt9
            5+9DtWIPAgMBAAECggEABShqVEkFM+Ft2Cb+sWg68rxTtGWlmP7SKquJYIo5b4d8
            ACVVswQSEZ/zGAuktKqtKDlkDV7obWBLlpid77gGfWA61STtfETvprvJnc4XgIOW
            6Hmgek0YhXFVVYMmdshtgcaGf4W6L41nIrf+AUbuHpQxUo2ibkGh3WncAU/xuqdL
            7T/FYOJGjhFMyJAkNhdDeEvHCcgrA9aADmjEQQYRSTjX4wrL3ALOrKDuYXdDP4hR
            4hFNdGRc07VP2mz6GzkKru3VMSLuTlmJtsiMcIrTp33iTpZK0pamCBLk6OGr2RbH
            bHNTtCvTLq8901SqDz53VzvVoLqWQ2i08WJLbascAQKBgQD/LnKpP27wZpZAVsC6
            rYbbPtZRObry9cUD+Z3TvnaT6oRToW2dzNbkINpBFzjGPM3TtXCXIFUSF6/45XBu
            ONX7mjfuulEVr5YOJNWUh9vfjnuZjo7Grw5YIa0yPkVJd0YB9jq2UJkEJlvo177E
            jY6fgh+LIuFfx1Zw6FS7xx32AQKBgQC4AIedpolKeriTVR/Ad7TRE1lDn9x82Q+y
            +niEXcmrmM83otWYthASdxScYeuo9FynowhiTxn6FbMOmnyyolLLUlwkQcZcdROR
            yNZo2yF+cSvDg/V7qHSs2KzVAFEeUlfQVzTYc5+MJxlk/cjh4Zm7h3VWVqJBPVSv
            antV8KP4DwKBgQC7XWdjTegvK6P26bvpVbBHGwRR74mNC1f1azqvVpHKWc9/eG/8
            BYNjTZvzXxGYvNyELhzVWjAccLgMkKrUw3aansmix7rxqVMMX49S185hf0TRoxLC
            X5awr0l0MrS9FI6asii55MP1gBTMCl1QBIBMLkbq6lmA8eROUsikd7dQAQKBgQCQ
            xAnu5RnbOVaCxFRo70WZwSlX5SxqJbUOUbYEHm4Ozfkqgrien49hl8Lljr0Efs1v
            LvvnrOh5NB1efflh6ghN44yPEhjooUw2RNc8RDvD6XJPL0Eye0TgwNCp/MfVnV9t
            kU8IhV+fuxtls64a2Y5EVrzgouShg4lfQd2rrdqzzQKBgQDkpn0IL0DA7laN8Fu3
            6G7dxZpFdfsrONE5CeVnyMcCk9NvULBotTQl8kjU4tYy2Jh+cLPj0GvO2lkRDUon
            ImlKOGBUEFe0kO+l7Az6dp1qptyQaT4Qo52MN7nL7CVPfjeygQAdB3brPr/uqsww
            Ba1LIiHFVP7RMXpa6Xkk3mh4Cg==
            -----END PRIVATE KEY-----
            
      Events:
        SQSTrigger:
          Type: SQS
          Properties:
            BatchSize: 10
            Queue: arn:aws:sqs:us-east-1:928084763632:Redox-Webhook  # Update SQS ARN as needed

Outputs:
  PdfToBase64LambdaArn:
    Description: "ARN of the PDF-to-Base64 Lambda function"
    Value: !GetAtt PdfToBase64Lambda.Arn

  SqsProcessingLambdaFunctionArn:
    Description: "ARN of the SQS Processing Lambda function"
    Value: !GetAtt SqsProcessingLambdaFunction.Arn
